# crypt

In [12]:
from itertools import permutations
import copy

def get_value(word,sub):
    s=0
    fact=1
    for letter in reversed(word):
        s=s+fact*sub[letter]
        fact*=10
    return s

def fun(string):
    l,r=string.lower().split('=')
    l=l.split('+')
    let=set(r)
    # print(let)
    for word in l:
        for letter in word:
            let.add(letter)
    let=list(let)
    dig=range(10)
    for perm in permutations(dig,len(let)):
        sol=dict(zip(let,perm))
        if sum(get_value(word,sol) for word in l)==get_value(r,sol):
            print('+'.join(str(get_value(word,sol)) for word in l)+"={} (mapping:{})".format(get_value(r,sol),sol))
            # print(sol)

fun("BASE+BALL=GAMES")

2461+2455=4916 (mapping:{'s': 6, 'e': 1, 'a': 4, 'b': 2, 'l': 5, 'm': 9, 'g': 0})
2483+2455=4938 (mapping:{'s': 8, 'e': 3, 'a': 4, 'b': 2, 'l': 5, 'm': 9, 'g': 0})
7483+7455=14938 (mapping:{'s': 8, 'e': 3, 'a': 4, 'b': 7, 'l': 5, 'm': 9, 'g': 1})


In [20]:
l=list(map(int,input().split()))

def trav(tree,flag):
    while(len(tree)>1):
        l=[]
        while(len(tree)>1):
            m1=tree.pop(0)
            m2=tree.pop(0)
            if flag:
                l.append(max(m1,m2))
            else:
                l.append(min(m1,m2))
        tree=l
        if flag:
            flag=0
        else:
            flag=1
        print(tree)
trav(l,int(input('ENter Falg')))


[5, 9, 12, 23]
[5, 12]
[12]


In [36]:
MAX, MIN = 1000, -1000
import math
def minimax(depth, nodeIndex, maximizingPlayer,values, alpha, beta):
    if depth == Depth:
        return values[nodeIndex]
    if maximizingPlayer:
        best = MIN
        for i in range(0, 2):
            if (nodeIndex * 2 + i<len(values)):
                val = minimax(depth + 1, nodeIndex * 2 + i,False, values, alpha, beta)
            else:
                val=0
            best = max(best, val)
            alpha = max(alpha, best)
            if beta <= alpha:
                break
        return best
    else:
        best = MAX
        for i in range(0, 2):
            if (nodeIndex * 2 + i<len(values)):
                val = minimax(depth + 1, nodeIndex * 2 + i,True, values, alpha, beta)
            else:
                val=0
            best = min(best, val)
            beta = min(beta, best)
            if beta <= alpha:
                break
            # print(val,end=' ')
        return best
      

values = [3, 5, 6, 9, 1] 
Depth =math.ceil( math.log(len(values),2))
print("The optimal value is :", minimax(0, 0, True, values, MIN, MAX))

The optimal value is : 5


In [42]:
def bds(d,start,goal):
    st=[start,]
    en=[goal,]
    vis_s=[]
    vis_e=[]
    while(1):
        s1=st.pop(0)
        for i in d[s1]:
            if i not in vis_e:
                st.append(i)
            else:
                vis_s.append(s1)
                vis_s.append(i)
                print(vis_s)
                print(vis_e)
                print("path founded")
                return 1
        vis_s.append(s1)
        e1=en.pop(0)
        for i in d[e1]:
            if i not in vis_s:
                en.append(i)
            else:
                vis_e.append(e1)
                vis_e.append(i)
                print(vis_s)
                print(vis_e)
                print("path founded")
                return 1
        vis_e.append(e1)

d={'a':['b','c'],'b':['d','e'],'c':['f','g'],'d':['b'],'e':['b'],'f':['c'],'g':['c']}
start='a'
end='g'
bds(d,start,end)


In [48]:
'''
    DFS
'''

def update(open,l):
    for i in l:
        if i not in open:
            open.append(i)
    return open


graph = {'A':['B', 'C', 'D'], 'B':['E', 'F'], 'C':['F', 'G'], 'E':['H', 'I'], 'F':['J']}

open=['A']
close=[]

while(open!=[]):
    m=open.pop(0)
    if m=='G':
        print('Reached')
        break
    else:
        if m in graph:
            open=update(open,graph[m])
            close.append(m)
    print(open,'    ',close)

['B', 'C', 'D']      ['A']
['C', 'D', 'E', 'F']      ['A', 'B']
['D', 'E', 'F', 'G']      ['A', 'B', 'C']
['E', 'F', 'G']      ['A', 'B', 'C']
['F', 'G', 'H', 'I']      ['A', 'B', 'C', 'E']
['G', 'H', 'I', 'J']      ['A', 'B', 'C', 'E', 'F']
Reached


In [52]:
'''
    Iterative Deepening Search
'''

def iddfs(graph, start, goal, depth):
    visited = set()
    stack = [(start, 0)]
    while stack:
        node, current_depth = stack.pop()
        if node == goal:
            return current_depth
        if node not in visited:
            visited.add(node)
            for neighbor in graph[node]:
                if current_depth < depth:
                    stack.append((neighbor, current_depth + 1))
    return -1

if __name__ == "__main__":
    graph = {
        "A": ["B", "C"],
        "B": ["D", "E"],
        "C": ["F", "G"],
        "D": ["H"],
        "E": ["I"],
        "F": ["J"],
        "G": ["K"],
        "H": [],
        "I": [],
        "J": [],
        "K": [],
    }
    print(iddfs(graph, "A", "K", 3))

3


In [60]:
'''
    Uniform Cost Search
'''



graph=[[] for i in range(8)]

graph[0].append(1)
graph[0].append(3)
graph[3].append(1)
graph[3].append(6)
graph[3].append(4)
graph[1].append(6)
graph[4].append(2)
graph[4].append(5)
graph[2].append(1)
graph[5].append(2)
graph[5].append(6)
graph[6].append(4)

cost={}
cost[(0, 1)] = 2
cost[(0, 3)] = 5
cost[(1, 6)] = 1
cost[(3, 1)] = 5
cost[(3, 6)] = 6
cost[(3, 4)] = 2
cost[(2, 1)] = 4
cost[(4, 2)] = 4
cost[(4, 5)] = 3
cost[(5, 2)] = 6
cost[(5, 6)] = 3
cost[(6, 4)] = 7


def uniform(start,goal,graph,cost):
    
    open=[[0,start]]
    visited=[]
    while(open!=[]):
        open.sort()
        cos,node=open.pop(0)

        if node==goal:
            return cos
        if node not in visited:
            visited.append(node)
            for i in graph[node]:
                open.append([cos+cost[(node,i)],i])
    else:
        return -1
uniform(0,5,graph,cost)

10

In [2]:
'''
    A Star algorithm
'''


from queue import PriorityQueue

def heuristic(node, goal):
    # Heuristic function to estimate the distance between a node and the goal
    # In this example, we use the difference in ASCII values of the nodes as the heuristic
    return abs(ord(node) - ord(goal))

def a_star(graph, start, goal):
    open_list = PriorityQueue()
    open_list.put((0, start))
    
    g_score = {node: float('inf') for node in graph}
    g_score[start] = 0
    
    f_score = {node: float('inf') for node in graph}
    f_score[start] = heuristic(start, goal)
    
    came_from = {}
    
    while not open_list.empty():
        _, current_node = open_list.get()
        
        if current_node == goal:
            path = reconstruct_path(came_from, current_node)
            path.reverse()
            print("Goal reached! Path:", ' -> '.join(path))
            return True
        
        neighbors = graph[current_node]
        
        for neighbor in neighbors:
            tentative_g_score = g_score[current_node] + 1  # Assuming the cost of each step is 1
            
            if tentative_g_score < g_score[neighbor]:
                g_score[neighbor] = tentative_g_score
                f_score[neighbor] = tentative_g_score + heuristic(neighbor, goal)
                open_list.put((f_score[neighbor], neighbor))
                came_from[neighbor] = current_node
    
    print("Goal not found!")
    return False

def reconstruct_path(came_from, current_node):
    path = [current_node]
    while current_node in came_from:
        current_node = came_from[current_node]
        path.append(current_node)
    return path


# Example usage:

# Define the graph as an adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D'],
    'C': ['A', 'E'],
    'D': ['B', 'F'],
    'E': ['C', 'F', 'G'],
    'F': ['D', 'E', 'H'],
    'G': ['E', 'H'],
    'H': ['F', 'G']
}

# Define the start and goal nodes
start_node = 'A'
goal_node = 'H'

# Run the A* algorithm
a_star(graph, start_node, goal_node)


Goal reached! Path: A -> C -> E -> G -> H


True

In [15]:
'''
    8-puzzle problem
'''

from queue import PriorityQueue
import numpy as np

# Define the goal state
goal_state = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])

# Define the heuristic function (Manhattan distance)
def heuristic(state):
    return np.sum(state != goal_state)

# Define the A* algorithm function
def solve_puzzle(start_state):
    open_list = PriorityQueue()
    open_list.put((0, start_state))
    closed_list = set()
    parent_map = {}  # Store the parent nodes for path tracing

    while not open_list.empty():
        _, current_state = open_list.get()

        if np.array_equal(current_state, goal_state):
            # Trace the path from the goal state to the start state
            path = []
            node = current_state
            while node is not None:
                path.append(node)
                node = parent_map.get(tuple(node.flatten()), None)
            path.reverse()
            return path

        closed_list.add(tuple(current_state.flatten()))

        zero_row, zero_col = np.where(current_state == 0)
        zero_row, zero_col = zero_row[0], zero_col[0]

        for move in [(0, -1), (0, 1), (-1, 0), (1, 0)]:
            new_state = np.copy(current_state)
            new_row, new_col = zero_row + move[0], zero_col + move[1]

            if 0 <= new_row < 3 and 0 <= new_col < 3:
                new_state[zero_row, zero_col], new_state[new_row, new_col] = (
                    new_state[new_row, new_col], new_state[zero_row, zero_col])

                if tuple(new_state.flatten()) not in closed_list:
                    open_list.put((heuristic(new_state), new_state))
                    parent_map[tuple(new_state.flatten())] = current_state

    return None

# Example usage:

# Define the start state
start_state = np.array([[1, 2, 3], [4, 5, 6], [0, 7, 8]])

# Solve the puzzle and trace the path
solution_path = solve_puzzle(start_state)

if solution_path is not None:
    print("Solution found!")
    for state in solution_path:
        print(state)
else:
    print("No solution found.")


Solution found!
[[1 2 3]
 [4 5 6]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [20]:
'''
    vaccum world problem - bfs
'''

from collections import deque

# Define the Vacuum World problem
class VacuumWorld:
    def __init__(self, state):
        self.state = state

    def get_possible_actions(self):
        if self.state[0] == 'A':
            return ['Clean', 'Right']
        elif self.state[0] == 'B':
            return ['Clean', 'Left']
    
    def get_successor(self, action):
        if action == 'Clean':
            if self.state[0] == 'A':
                return VacuumWorld(('A', self.state[1]))
            elif self.state[0] == 'B':
                return VacuumWorld(('B', self.state[1]))
        elif action == 'Right':
            return VacuumWorld(('B', self.state[1]))
        elif action == 'Left':
            return VacuumWorld(('A', self.state[1]))

    def is_goal_state(self):
        return self.state[1] == 'Clean'

# Define the Breadth-First Search algorithm
def bfs(initial_state):
    initial_node = VacuumWorld(initial_state)
    if initial_node.is_goal_state():
        return initial_node.state

    frontier = deque([initial_node])
    explored = set()

    while frontier:
        current_node = frontier.popleft()
        explored.add(current_node.state)

        actions = current_node.get_possible_actions()
        for action in actions:
            successor = current_node.get_successor(action)
            if successor.state not in explored and successor not in frontier:
                if successor.is_goal_state():
                    return successor.state
                frontier.append(successor)

    return None

# Example usage:

# Define the initial state
initial_state = ('A', 'Dirty')

# Solve the Vacuum World problem using BFS
goal_state = bfs(initial_state)

if goal_state is not None:
    print("Goal state found:", goal_state)
else:
    print("Goal state not found.")


Goal state not found.


In [25]:
'''
    Missionaries And Caniballs - BFS
'''

M = int(input("Enter no. of Missionaries: "))
C = int(input("Enter no. of Cannibals: "))
root = [[M, C, 1], [0, 0, 0]]
goal = [[0, 0, 0], [M, C, 1]]

def Missionaries_and_Cannibals_BFS(r, g, m, c):
    open_list = []
    closed_list = []
    open_list.append(r)
    graph = {}
    moves = {}
    while g not in open_list:
        current_state = open_list.pop(0)
        closed_list.append(current_state)
        m1, c1, m2, c2 = current_state[0][0], current_state[0][1], current_state[1][0], current_state[1][1]
        possible_moves = []
        if current_state[0][2] == 1:  # boat is on the left side
            if m1 >= 2 and (m1 - 2 >= c1 or m1 - 2 == 0) and m2 + 2 >= c2:
                possible_moves.append([[m1 - 2, c1, 0], [m2 + 2, c2, 1]])
            if m1 >= 1 and c1 >= 1 and m1 - 1 >= c1 - 1 and m2 + 1 >= c2 + 1:
                possible_moves.append([[m1 - 1, c1 - 1, 0], [m2 + 1, c2 + 1, 1]])
            if c1 >= 2 and (m2 >= c2 + 2 or m2 == 0):
                possible_moves.append([[m1, c1 - 2, 0], [m2, c2 + 2, 1]])
            if m1 >= 1 and (m1 - 1 >= c1 or m1 - 1 == 0) and m2 + 1 >= c2:
                possible_moves.append([[m1 - 1, c1, 0], [m2 + 1, c2, 1]])
            if c1 >= 1 and (m2 >= c2 + 1 or m2 == 0):
                possible_moves.append([[m1, c1 - 1, 0], [m2, c2 + 1, 1]])
        elif current_state[1][2] == 1:  # boat is on the right side
            if m2 >= 2 and m1 + 2 >= c1 and (m2 - 2 >= c2 or m2 - 2 == 0):
                possible_moves.append([[m1 + 2, c1, 1], [m2 - 2, c2, 0]])
            if m2 >= 1 and c2 >= 1 and m1 + 1 >= c1 + 1 and m2 - 1 >= c2 - 1:
                possible_moves.append([[m1 + 1, c1 + 1, 1], [m2 - 1, c2 - 1, 0]])
            if c2 >= 2 and ((m1 >= c1 + 2 and m2 >= c2 - 2) or m1 == 0):
                possible_moves.append([[m1, c1 + 2, 1], [m2, c2 - 2, 0]])
            if m2 >= 1 and m1 + 1 >= c1 and (m2 - 1 >= c2 or m2 - 1 == 0):
                possible_moves.append([[m1 + 1, c1, 1], [m2 - 1, c2, 0]])
            if c2 >= 1 and (m1 >= c1 + 1 or m1 == 0):
                possible_moves.append([[m1, c1 + 1, 1], [m2, c2 - 1, 0]])

        for move in possible_moves:
            if move not in closed_list and move not in open_list:
                open_list.append(move)
                moves[str(move)] = current_state

    path = [str(g)]
    current_state = g
    while current_state != r:
        current_state = moves[str(current_state)]
        path.append(str(current_state))

    return path[::-1]

path = Missionaries_and_Cannibals_BFS(root, goal, M, C)

if path is not None:
    print("Moves to reach the goal state:")
    for move in path:
        print(move)
else:
    print("Goal state not found.")


Moves to reach the goal state:
[[3, 3, 1], [0, 0, 0]]
[[2, 2, 0], [1, 1, 1]]
[[3, 2, 1], [0, 1, 0]]
[[3, 0, 0], [0, 3, 1]]
[[3, 1, 1], [0, 2, 0]]
[[1, 1, 0], [2, 2, 1]]
[[2, 2, 1], [1, 1, 0]]
[[0, 2, 0], [3, 1, 1]]
[[0, 3, 1], [3, 0, 0]]
[[0, 1, 0], [3, 2, 1]]
[[1, 1, 1], [2, 2, 0]]
[[0, 0, 0], [3, 3, 1]]
